name: example
description: "Example app demonstrating fk_booster package usage."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  fk_booster:
    path: ../
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.9.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
